### PR TITLE
fixed commands and added nginx reverse proxy

### PR DESCRIPTION
**Pull request by masterlan**
fixed some commands as they didn’t work and have not been homogenous
(sudo usage); added nginx installation and reverse proxy configuration

### CODE REVIEW

**Comment by masterlan** [comment]
I used CentOS 7 and rpm packages, but the webserver has not been installed and configured automatically. I was also not aware of the configuration in this directory. Therefore, a hint might be useful.

**Comment by monotek** [comment]
It's not in the 1.0.0 packages. Use the packages from the develop branch or wait for the next release.


Working Develop build: https://packager.io/gh/zammad/zammad/install?bid=1216#centos-7-zammad

**Comment by monotek** [comment]
@martini

This merge will break Installation of current packager.io packages from develop branch, which already have nginx Installation & configurstion included.

**Comment by martini** [comment]
@monotek should I undo the change?

**Comment by monotek** [comment]
Yes for the nginx.conf Part.

**Pull request merged**
